// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (
    user_external_id
) VALUES (
    $1
)
RETURNING chat_id, chat_external_id, user_external_id, status, created_at, updated_at
`

func (q *Queries) CreateChat(ctx context.Context, userExternalID uuid.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, userExternalID)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.ChatExternalID,
		&i.UserExternalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChatStatus = `-- name: DeleteChatStatus :exec
DELETE FROM chats
WHERE chat_external_id = $1
`

func (q *Queries) DeleteChatStatus(ctx context.Context, chatExternalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChatStatus, chatExternalID)
	return err
}

const getChat = `-- name: GetChat :one
SELECT chat_id, chat_external_id, user_external_id, status, created_at, updated_at FROM chats
WHERE chat_external_id = $1
`

func (q *Queries) GetChat(ctx context.Context, chatExternalID uuid.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, chatExternalID)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.ChatExternalID,
		&i.UserExternalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChats = `-- name: ListChats :many
SELECT chat_id, chat_external_id, user_external_id, status, created_at, updated_at FROM chats
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListChatsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListChats(ctx context.Context, arg ListChatsParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listChats, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatExternalID,
			&i.UserExternalID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatStatus = `-- name: UpdateChatStatus :exec
UPDATE chats
SET status = $2,
    updated_at = NOW()
WHERE chat_external_id = $1
`

type UpdateChatStatusParams struct {
	ChatExternalID uuid.UUID `json:"chat_external_id"`
	Status         string    `json:"status"`
}

func (q *Queries) UpdateChatStatus(ctx context.Context, arg UpdateChatStatusParams) error {
	_, err := q.db.Exec(ctx, updateChatStatus, arg.ChatExternalID, arg.Status)
	return err
}
