// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (
    user_external_id,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, NOW(), NOW()
)
RETURNING chat_id, chat_external_id, user_external_id, status, created_at, updated_at
`

type CreateChatParams struct {
	UserExternalID uuid.UUID `json:"user_external_id"`
	Status         string    `json:"status"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.UserExternalID, arg.Status)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.ChatExternalID,
		&i.UserExternalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChatDefaults = `-- name: CreateChatDefaults :one
INSERT INTO chats (
    user_external_id,
    created_at,
    updated_at
) VALUES (
    $1, NOW(), NOW()
)
RETURNING chat_id, chat_external_id, user_external_id, status, created_at, updated_at
`

func (q *Queries) CreateChatDefaults(ctx context.Context, userExternalID uuid.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, createChatDefaults, userExternalID)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.ChatExternalID,
		&i.UserExternalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats
WHERE chat_external_id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, chatExternalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChat, chatExternalID)
	return err
}

const getChat = `-- name: GetChat :one
SELECT chat_id, chat_external_id, user_external_id, status, created_at, updated_at FROM chats
WHERE chat_external_id = $1
`

func (q *Queries) GetChat(ctx context.Context, chatExternalID uuid.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, chatExternalID)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.ChatExternalID,
		&i.UserExternalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatsByUser = `-- name: GetChatsByUser :many
SELECT chat_id, chat_external_id, user_external_id, status, created_at, updated_at FROM chats
WHERE user_external_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetChatsByUserParams struct {
	UserExternalID uuid.UUID `json:"user_external_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) GetChatsByUser(ctx context.Context, arg GetChatsByUserParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getChatsByUser, arg.UserExternalID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatExternalID,
			&i.UserExternalID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChats = `-- name: ListChats :many
SELECT chat_id, chat_external_id, user_external_id, status, created_at, updated_at FROM chats
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListChatsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListChats(ctx context.Context, arg ListChatsParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listChats, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatExternalID,
			&i.UserExternalID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChat = `-- name: UpdateChat :one
UPDATE chats
SET
user_external_id = COALESCE(NULLIF($2, '00000000-0000-0000-0000-000000000000'::uuid), user_external_id),
    status = COALESCE($3, status),
    updated_at = NOW()
WHERE chat_external_id = $1
RETURNING chat_id, chat_external_id, user_external_id, status, created_at, updated_at
`

type UpdateChatParams struct {
	ChatExternalID uuid.UUID   `json:"chat_external_id"`
	Column2        interface{} `json:"column_2"`
	Status         string      `json:"status"`
}

func (q *Queries) UpdateChat(ctx context.Context, arg UpdateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, updateChat, arg.ChatExternalID, arg.Column2, arg.Status)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.ChatExternalID,
		&i.UserExternalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChatStatus = `-- name: UpdateChatStatus :one
UPDATE chats
SET status = $2,
    updated_at = NOW()
WHERE chat_external_id = $1
RETURNING chat_id, chat_external_id, user_external_id, status, created_at, updated_at
`

type UpdateChatStatusParams struct {
	ChatExternalID uuid.UUID `json:"chat_external_id"`
	Status         string    `json:"status"`
}

func (q *Queries) UpdateChatStatus(ctx context.Context, arg UpdateChatStatusParams) (Chat, error) {
	row := q.db.QueryRow(ctx, updateChatStatus, arg.ChatExternalID, arg.Status)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.ChatExternalID,
		&i.UserExternalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
