// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    chat_external_id,
    sender_external_id,
    content,
    is_system_message,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
)
RETURNING message_id, message_external_id, chat_external_id, sender_external_id, content, is_system_message, created_at, updated_at
`

type CreateMessageParams struct {
	ChatExternalID   uuid.UUID `json:"chat_external_id"`
	SenderExternalID uuid.UUID `json:"sender_external_id"`
	Content          string    `json:"content"`
	IsSystemMessage  bool      `json:"is_system_message"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChatExternalID,
		arg.SenderExternalID,
		arg.Content,
		arg.IsSystemMessage,
	)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.MessageExternalID,
		&i.ChatExternalID,
		&i.SenderExternalID,
		&i.Content,
		&i.IsSystemMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE message_external_id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, messageExternalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, messageExternalID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT message_id, message_external_id, chat_external_id, sender_external_id, content, is_system_message, created_at, updated_at FROM messages
WHERE message_external_id = $1
`

func (q *Queries) GetMessage(ctx context.Context, messageExternalID uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, messageExternalID)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.MessageExternalID,
		&i.ChatExternalID,
		&i.SenderExternalID,
		&i.Content,
		&i.IsSystemMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessagesByChat = `-- name: ListMessagesByChat :many
SELECT message_id, message_external_id, chat_external_id, sender_external_id, content, is_system_message, created_at, updated_at FROM messages
WHERE chat_external_id = $1
ORDER BY created_at ASC
LIMIT $2
OFFSET $3
`

type ListMessagesByChatParams struct {
	ChatExternalID uuid.UUID `json:"chat_external_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListMessagesByChat(ctx context.Context, arg ListMessagesByChatParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByChat, arg.ChatExternalID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.MessageID,
			&i.MessageExternalID,
			&i.ChatExternalID,
			&i.SenderExternalID,
			&i.Content,
			&i.IsSystemMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessagesByChat = `-- name: ListRecentMessagesByChat :many
SELECT message_id, message_external_id, chat_external_id, sender_external_id, content, is_system_message, created_at, updated_at FROM messages
WHERE chat_external_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentMessagesByChatParams struct {
	ChatExternalID uuid.UUID `json:"chat_external_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListRecentMessagesByChat(ctx context.Context, arg ListRecentMessagesByChatParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listRecentMessagesByChat, arg.ChatExternalID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.MessageID,
			&i.MessageExternalID,
			&i.ChatExternalID,
			&i.SenderExternalID,
			&i.Content,
			&i.IsSystemMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET content = $2,
    updated_at = NOW()
WHERE message_external_id = $1
RETURNING message_id, message_external_id, chat_external_id, sender_external_id, content, is_system_message, created_at, updated_at
`

type UpdateMessageParams struct {
	MessageExternalID uuid.UUID `json:"message_external_id"`
	Content           string    `json:"content"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.MessageExternalID, arg.Content)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.MessageExternalID,
		&i.ChatExternalID,
		&i.SenderExternalID,
		&i.Content,
		&i.IsSystemMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
