// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatStatusType string

const (
	ChatStatusTypeOpen    ChatStatusType = "open"
	ChatStatusTypePending ChatStatusType = "pending"
	ChatStatusTypeClosed  ChatStatusType = "closed"
)

func (e *ChatStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatStatusType(s)
	case string:
		*e = ChatStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatStatusType: %T", src)
	}
	return nil
}

type NullChatStatusType struct {
	ChatStatusType ChatStatusType `json:"chat_status_type"`
	Valid          bool           `json:"valid"` // Valid is true if ChatStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatStatusType), nil
}

type RoleType string

const (
	RoleTypeSuperadmin RoleType = "superadmin"
	RoleTypeAdmin      RoleType = "admin"
	RoleTypeUser       RoleType = "user"
	RoleTypeGuest      RoleType = "guest"
	RoleTypeSystem     RoleType = "system"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType `json:"role_type"`
	Valid    bool     `json:"valid"` // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type Chat struct {
	ChatID         pgtype.Int8      `json:"chat_id"`
	ChatExternalID uuid.UUID        `json:"chat_external_id"`
	UserExternalID uuid.UUID        `json:"user_external_id"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Message struct {
	MessageID         pgtype.Int8      `json:"message_id"`
	MessageExternalID uuid.UUID        `json:"message_external_id"`
	ChatExternalID    uuid.UUID        `json:"chat_external_id"`
	SenderExternalID  uuid.UUID        `json:"sender_external_id"`
	Content           string           `json:"content"`
	IsSystemMessage   bool             `json:"is_system_message"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	UserID         pgtype.Int8      `json:"user_id"`
	UserExternalID uuid.UUID        `json:"user_external_id"`
	Name           string           `json:"name"`
	Username       pgtype.Text      `json:"username"`
	PhoneNumber    pgtype.Text      `json:"phone_number"`
	Email          pgtype.Text      `json:"email"`
	Password       pgtype.Text      `json:"password"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
