// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const blockSession = `-- name: BlockSession :exec
UPDATE sessions
SET is_blocked = true, updated_at = now()
WHERE session_external_id = $1
`

func (q *Queries) BlockSession(ctx context.Context, sessionExternalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, blockSession, sessionExternalID)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  user_agent, username, user_external_id, is_blocked, client_ip, refresh_token, expires_at
) VALUES (
  $1, $2, $3, COALESCE($4, false), $5, $6, $7
)
RETURNING session_id, session_external_id, user_agent, username, user_external_id, is_blocked, client_ip, refresh_token, created_at, updated_at, expires_at
`

type CreateSessionParams struct {
	UserAgent      string      `json:"user_agent"`
	Username       string      `json:"username"`
	UserExternalID uuid.UUID   `json:"user_external_id"`
	Column4        interface{} `json:"column_4"`
	ClientIp       string      `json:"client_ip"`
	RefreshToken   string      `json:"refresh_token"`
	ExpiresAt      time.Time   `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserAgent,
		arg.Username,
		arg.UserExternalID,
		arg.Column4,
		arg.ClientIp,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.SessionExternalID,
		&i.UserAgent,
		&i.Username,
		&i.UserExternalID,
		&i.IsBlocked,
		&i.ClientIp,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE session_external_id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionExternalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, sessionExternalID)
	return err
}

const getSessionByExternalID = `-- name: GetSessionByExternalID :one
SELECT session_id, session_external_id, user_agent, username, user_external_id, is_blocked, client_ip, refresh_token, created_at, updated_at, expires_at FROM sessions
WHERE session_external_id = $1 LIMIT 1
`

func (q *Queries) GetSessionByExternalID(ctx context.Context, sessionExternalID uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByExternalID, sessionExternalID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.SessionExternalID,
		&i.UserAgent,
		&i.Username,
		&i.UserExternalID,
		&i.IsBlocked,
		&i.ClientIp,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const isUserOnline = `-- name: IsUserOnline :one
SELECT EXISTS (
    SELECT 1 FROM sessions
    WHERE user_external_id = $1
      AND is_blocked = false
      AND expires_at > now()
) AS is_online
`

func (q *Queries) IsUserOnline(ctx context.Context, userExternalID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserOnline, userExternalID)
	var is_online bool
	err := row.Scan(&is_online)
	return is_online, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT session_id, session_external_id, user_agent, username, user_external_id, is_blocked, client_ip, refresh_token, created_at, updated_at, expires_at FROM sessions
WHERE user_external_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userExternalID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userExternalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.SessionID,
			&i.SessionExternalID,
			&i.UserAgent,
			&i.Username,
			&i.UserExternalID,
			&i.IsBlocked,
			&i.ClientIp,
			&i.RefreshToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionToken = `-- name: UpdateSessionToken :one
UPDATE sessions
SET refresh_token = $2,
    updated_at = now(),
    expires_at = $3
WHERE session_external_id = $1
RETURNING session_id, session_external_id, user_agent, username, user_external_id, is_blocked, client_ip, refresh_token, created_at, updated_at, expires_at
`

type UpdateSessionTokenParams struct {
	SessionExternalID uuid.UUID `json:"session_external_id"`
	RefreshToken      string    `json:"refresh_token"`
	ExpiresAt         time.Time `json:"expires_at"`
}

func (q *Queries) UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionToken, arg.SessionExternalID, arg.RefreshToken, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.SessionExternalID,
		&i.UserAgent,
		&i.Username,
		&i.UserExternalID,
		&i.IsBlocked,
		&i.ClientIp,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
