// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_account.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_account (
    user_external_id,
    updated_at
) VALUES (
    $1, NOW()
)
RETURNING account_id, account_external_id, user_external_id, status, birth_date, photos, updated_at
`

func (q *Queries) CreateUserAccount(ctx context.Context, userExternalID uuid.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUserAccount, userExternalID)
	var i UserAccount
	err := row.Scan(
		&i.AccountID,
		&i.AccountExternalID,
		&i.UserExternalID,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserAccount = `-- name: DeleteUserAccount :exec
DELETE FROM user_account
WHERE account_external_id = $1
`

func (q *Queries) DeleteUserAccount(ctx context.Context, accountExternalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserAccount, accountExternalID)
	return err
}

const getUserAccountByAccountID = `-- name: GetUserAccountByAccountID :one
SELECT
    u.name,
    u.username,
    u.email,
    u.role,
    a.account_external_id,
    a.status,
    a.birth_date,
    a.photos
FROM user_account a
INNER JOIN users u
    ON a.user_external_id = u.user_external_id
WHERE a.account_external_id = $1
LIMIT 1
`

type GetUserAccountByAccountIDRow struct {
	Name              string        `json:"name"`
	Username          pgtype.Text   `json:"username"`
	Email             pgtype.Text   `json:"email"`
	Role              string        `json:"role"`
	AccountExternalID uuid.UUID     `json:"account_external_id"`
	Status            AccountStatus `json:"status"`
	BirthDate         pgtype.Date   `json:"birth_date"`
	Photos            []string      `json:"photos"`
}

func (q *Queries) GetUserAccountByAccountID(ctx context.Context, accountExternalID uuid.UUID) (GetUserAccountByAccountIDRow, error) {
	row := q.db.QueryRow(ctx, getUserAccountByAccountID, accountExternalID)
	var i GetUserAccountByAccountIDRow
	err := row.Scan(
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.AccountExternalID,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
	)
	return i, err
}

const getUserAccountByExternalID = `-- name: GetUserAccountByExternalID :one
SELECT
    u.name,
    u.username,
    u.email,
    u.role,
    a.account_external_id,
    a.status,
    a.birth_date,
    a.photos
FROM users u
INNER JOIN user_account a 
    ON u.user_external_id = a.user_external_id
WHERE u.user_external_id = $1
LIMIT 1
`

type GetUserAccountByExternalIDRow struct {
	Name              string        `json:"name"`
	Username          pgtype.Text   `json:"username"`
	Email             pgtype.Text   `json:"email"`
	Role              string        `json:"role"`
	AccountExternalID uuid.UUID     `json:"account_external_id"`
	Status            AccountStatus `json:"status"`
	BirthDate         pgtype.Date   `json:"birth_date"`
	Photos            []string      `json:"photos"`
}

func (q *Queries) GetUserAccountByExternalID(ctx context.Context, userExternalID uuid.UUID) (GetUserAccountByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getUserAccountByExternalID, userExternalID)
	var i GetUserAccountByExternalIDRow
	err := row.Scan(
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.AccountExternalID,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
	)
	return i, err
}

const updateUserAccountProfile = `-- name: UpdateUserAccountProfile :one
UPDATE user_account
SET
    birth_date = $2,
    photos = $3,
    updated_at = NOW()
WHERE user_external_id = $1
RETURNING account_id, account_external_id, user_external_id, status, birth_date, photos, updated_at
`

type UpdateUserAccountProfileParams struct {
	UserExternalID uuid.UUID   `json:"user_external_id"`
	BirthDate      pgtype.Date `json:"birth_date"`
	Photos         []string    `json:"photos"`
}

func (q *Queries) UpdateUserAccountProfile(ctx context.Context, arg UpdateUserAccountProfileParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, updateUserAccountProfile, arg.UserExternalID, arg.BirthDate, arg.Photos)
	var i UserAccount
	err := row.Scan(
		&i.AccountID,
		&i.AccountExternalID,
		&i.UserExternalID,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAccountStatus = `-- name: UpdateUserAccountStatus :one
UPDATE user_account
SET
    status = $2,
    updated_at = NOW()
WHERE user_external_id = $1
RETURNING account_id, account_external_id, user_external_id, status, birth_date, photos, updated_at
`

type UpdateUserAccountStatusParams struct {
	UserExternalID uuid.UUID     `json:"user_external_id"`
	Status         AccountStatus `json:"status"`
}

func (q *Queries) UpdateUserAccountStatus(ctx context.Context, arg UpdateUserAccountStatusParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, updateUserAccountStatus, arg.UserExternalID, arg.Status)
	var i UserAccount
	err := row.Scan(
		&i.AccountID,
		&i.AccountExternalID,
		&i.UserExternalID,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.UpdatedAt,
	)
	return i, err
}
