// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    username,
    phone_number,
    email,
    hashed_password,
    role,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
RETURNING user_id, user_external_id, name, username, phone_number, email, hashed_password, role, created_at, updated_at
`

type CreateUserParams struct {
	Name           string      `json:"name"`
	Username       pgtype.Text `json:"username"`
	PhoneNumber    pgtype.Text `json:"phone_number"`
	Email          pgtype.Text `json:"email"`
	HashedPassword pgtype.Text `json:"hashed_password"`
	Role           string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.PhoneNumber,
		arg.Email,
		arg.HashedPassword,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.Name,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_external_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userExternalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, userExternalID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT user_id, user_external_id, name, username, phone_number, email, hashed_password, role, created_at, updated_at FROM users
WHERE user_external_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userExternalID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userExternalID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.Name,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, user_external_id, name, username, phone_number, email, hashed_password, role, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.Name,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT 
  user_id, 
  user_external_id, 
  name, 
  username, 
  phone_number, 
  email, 
  hashed_password, 
  role, 
  created_at, 
  updated_at 
FROM users 
WHERE user_external_id = $1 LIMIT 1
`

func (q *Queries) GetUserByExternalID(ctx context.Context, userExternalID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, userExternalID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.Name,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, user_external_id, name, username, phone_number, email, hashed_password, role, created_at, updated_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.Name,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, user_external_id, name, username, phone_number, email, hashed_password, role, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.UserExternalID,
			&i.Name,
			&i.Username,
			&i.PhoneNumber,
			&i.Email,
			&i.HashedPassword,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = $2,
    username = $3,
    phone_number = $4,
    email = $5,
    role = $6,
    updated_at = NOW()
WHERE user_external_id = $1
RETURNING user_id, user_external_id, name, username, phone_number, email, hashed_password, role, created_at, updated_at
`

type UpdateUserParams struct {
	UserExternalID uuid.UUID   `json:"user_external_id"`
	Name           string      `json:"name"`
	Username       pgtype.Text `json:"username"`
	PhoneNumber    pgtype.Text `json:"phone_number"`
	Email          pgtype.Text `json:"email"`
	Role           string      `json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserExternalID,
		arg.Name,
		arg.Username,
		arg.PhoneNumber,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.Name,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET hashed_password = $2,
    updated_at = NOW()
WHERE user_external_id = $1
`

type UpdateUserPasswordParams struct {
	UserExternalID uuid.UUID   `json:"user_external_id"`
	HashedPassword pgtype.Text `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.UserExternalID, arg.HashedPassword)
	return err
}

const userUpdateUsernameAndEmail = `-- name: UserUpdateUsernameAndEmail :one
UPDATE users
SET
    username = $2,
    email = $3,
    updated_at = NOW()
WHERE user_external_id = $1
RETURNING user_id, user_external_id, name, username, phone_number, email, hashed_password, role, created_at, updated_at
`

type UserUpdateUsernameAndEmailParams struct {
	UserExternalID uuid.UUID   `json:"user_external_id"`
	Username       pgtype.Text `json:"username"`
	Email          pgtype.Text `json:"email"`
}

func (q *Queries) UserUpdateUsernameAndEmail(ctx context.Context, arg UserUpdateUsernameAndEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, userUpdateUsernameAndEmail, arg.UserExternalID, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.Name,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
