// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPhotoToUserProfile = `-- name: AddPhotoToUserProfile :one
UPDATE users
SET  
    photos = array_append(photos, $2),
    updated_at = NOW()
WHERE user_external_id = $1
RETURNING user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos, last_seen
`

type AddPhotoToUserProfileParams struct {
	UserExternalID uuid.UUID   `json:"user_external_id"`
	ArrayAppend    interface{} `json:"array_append"`
}

func (q *Queries) AddPhotoToUserProfile(ctx context.Context, arg AddPhotoToUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, addPhotoToUserProfile, arg.UserExternalID, arg.ArrayAppend)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.LastSeen,
	)
	return i, err
}

const addPhotosToUserProfile = `-- name: AddPhotosToUserProfile :one
UPDATE users
SET 
    photos = photos || $2,
    updated_at = NOW()
WHERE user_external_id = $1
RETURNING user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos, last_seen
`

type AddPhotosToUserProfileParams struct {
	UserExternalID uuid.UUID `json:"user_external_id"`
	Photos         []string  `json:"photos"`
}

func (q *Queries) AddPhotosToUserProfile(ctx context.Context, arg AddPhotosToUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, addPhotosToUserProfile, arg.UserExternalID, arg.Photos)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.LastSeen,
	)
	return i, err
}

const createGuestUser = `-- name: CreateGuestUser :one
INSERT INTO users (
    first_name,
    last_name,
    email,
    role,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
)
RETURNING user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos
`

type CreateGuestUserParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Role      string `json:"role"`
}

type CreateGuestUserRow struct {
	UserID         pgtype.Int8      `json:"user_id"`
	UserExternalID uuid.UUID        `json:"user_external_id"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Username       pgtype.Text      `json:"username"`
	PhoneNumber    pgtype.Text      `json:"phone_number"`
	Email          string           `json:"email"`
	HashedPassword pgtype.Text      `json:"hashed_password"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Status         AccountStatus    `json:"status"`
	BirthDate      pgtype.Date      `json:"birth_date"`
	Photos         []string         `json:"photos"`
}

func (q *Queries) CreateGuestUser(ctx context.Context, arg CreateGuestUserParams) (CreateGuestUserRow, error) {
	row := q.db.QueryRow(ctx, createGuestUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Role,
	)
	var i CreateGuestUserRow
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name,
    last_name,
    username,
    phone_number,
    email,
    hashed_password,
    role,
    status,
    birth_date,
    photos,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW()
)
RETURNING user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos
`

type CreateUserParams struct {
	FirstName      string        `json:"first_name"`
	LastName       string        `json:"last_name"`
	Username       pgtype.Text   `json:"username"`
	PhoneNumber    pgtype.Text   `json:"phone_number"`
	Email          string        `json:"email"`
	HashedPassword pgtype.Text   `json:"hashed_password"`
	Role           string        `json:"role"`
	Status         AccountStatus `json:"status"`
	BirthDate      pgtype.Date   `json:"birth_date"`
	Photos         []string      `json:"photos"`
}

type CreateUserRow struct {
	UserID         pgtype.Int8      `json:"user_id"`
	UserExternalID uuid.UUID        `json:"user_external_id"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Username       pgtype.Text      `json:"username"`
	PhoneNumber    pgtype.Text      `json:"phone_number"`
	Email          string           `json:"email"`
	HashedPassword pgtype.Text      `json:"hashed_password"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Status         AccountStatus    `json:"status"`
	BirthDate      pgtype.Date      `json:"birth_date"`
	Photos         []string         `json:"photos"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.PhoneNumber,
		arg.Email,
		arg.HashedPassword,
		arg.Role,
		arg.Status,
		arg.BirthDate,
		arg.Photos,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_external_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userExternalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, userExternalID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos, last_seen
FROM users
WHERE user_external_id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userExternalID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userExternalID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.LastSeen,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos, last_seen
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.LastSeen,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT 
  user_id, 
  user_external_id, 
  first_name,
  last_name, 
  username, 
  phone_number, 
  email, 
  hashed_password,
  role, 
  created_at, 
  updated_at,
  status, 
  birth_date, 
  photos,
  last_seen
FROM users 
WHERE user_external_id = $1
LIMIT 1
`

func (q *Queries) GetUserByExternalID(ctx context.Context, userExternalID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, userExternalID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.LastSeen,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos, last_seen
FROM users
WHERE phone_number = $1
LIMIT 1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.LastSeen,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos, last_seen
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.LastSeen,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos, last_seen
FROM users
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.UserExternalID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.PhoneNumber,
			&i.Email,
			&i.HashedPassword,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.BirthDate,
			&i.Photos,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE(NULLIF($2, ''), first_name),
    last_name = COALESCE(NULLIF($3, ''), last_name),
    username = COALESCE(NULLIF($4, ''), username),
    phone_number = COALESCE(NULLIF($5, ''), phone_number),
    email = COALESCE(NULLIF($6, ''), email),
    role = COALESCE($7, role),
    status = COALESCE($8, status),
    birth_date = COALESCE($9, birth_date),
    photos = COALESCE($10, photos),
    updated_at = NOW()
WHERE user_external_id = $1
RETURNING user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos, last_seen
`

type UpdateUserParams struct {
	UserExternalID uuid.UUID     `json:"user_external_id"`
	Column2        interface{}   `json:"column_2"`
	Column3        interface{}   `json:"column_3"`
	Column4        interface{}   `json:"column_4"`
	Column5        interface{}   `json:"column_5"`
	Column6        interface{}   `json:"column_6"`
	Role           string        `json:"role"`
	Status         AccountStatus `json:"status"`
	BirthDate      pgtype.Date   `json:"birth_date"`
	Photos         []string      `json:"photos"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserExternalID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Role,
		arg.Status,
		arg.BirthDate,
		arg.Photos,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.LastSeen,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET hashed_password = $2,
    updated_at = NOW()
WHERE user_external_id = $1
`

type UpdateUserPasswordParams struct {
	UserExternalID uuid.UUID   `json:"user_external_id"`
	HashedPassword pgtype.Text `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.UserExternalID, arg.HashedPassword)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET
    role = $2,
    updated_at = NOW()
WHERE user_external_id = $1
RETURNING user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos, last_seen
`

type UpdateUserRoleParams struct {
	UserExternalID uuid.UUID `json:"user_external_id"`
	Role           string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.UserExternalID, arg.Role)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.LastSeen,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET
    status = $2,
    updated_at = NOW()
WHERE user_external_id = $1
RETURNING user_id, user_external_id, first_name, last_name, username, phone_number, email, hashed_password, role, created_at, updated_at, status, birth_date, photos, last_seen
`

type UpdateUserStatusParams struct {
	UserExternalID uuid.UUID     `json:"user_external_id"`
	Status         AccountStatus `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.UserExternalID, arg.Status)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserExternalID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.BirthDate,
		&i.Photos,
		&i.LastSeen,
	)
	return i, err
}
